var annotated_dup =
[
    [ "zisa", "namespacezisa.html", [
      [ "detail", "namespacezisa_1_1detail.html", [
        [ "ErasedDataTypeFactory", "structzisa_1_1detail_1_1ErasedDataTypeFactory.html", null ]
      ] ],
      [ "internal", "namespacezisa_1_1internal.html", [
        [ "ScientificConstructorImpl", "structzisa_1_1internal_1_1ScientificConstructorImpl.html", null ],
        [ "ScientificConstructorImpl< T, typename std::enable_if<!std::is_trivially_copyable< T >::value >::type >", "structzisa_1_1internal_1_1ScientificConstructorImpl_3_01T_00_01typename_01std_1_1enable__if_3_9sdec2d795a2d274da029e96e9938ce3dd.html", null ]
      ] ],
      [ "cuda_memory_resource", "classzisa_1_1cuda__memory__resource.html", "classzisa_1_1cuda__memory__resource" ],
      [ "HDF5DataType", "classzisa_1_1HDF5DataType.html", "classzisa_1_1HDF5DataType" ],
      [ "HDF5File", "classzisa_1_1HDF5File.html", "classzisa_1_1HDF5File" ],
      [ "HDF5SerialWriter", "classzisa_1_1HDF5SerialWriter.html", "classzisa_1_1HDF5SerialWriter" ],
      [ "HDF5SerialReader", "classzisa_1_1HDF5SerialReader.html", "classzisa_1_1HDF5SerialReader" ],
      [ "HDF5Writer", "classzisa_1_1HDF5Writer.html", "classzisa_1_1HDF5Writer" ],
      [ "HDF5Reader", "classzisa_1_1HDF5Reader.html", "classzisa_1_1HDF5Reader" ],
      [ "HierarchicalFile", "classzisa_1_1HierarchicalFile.html", "classzisa_1_1HierarchicalFile" ],
      [ "HierarchicalReader", "classzisa_1_1HierarchicalReader.html", "classzisa_1_1HierarchicalReader" ],
      [ "HierarchicalWriter", "classzisa_1_1HierarchicalWriter.html", "classzisa_1_1HierarchicalWriter" ],
      [ "NetCDFFileStructure", "classzisa_1_1NetCDFFileStructure.html", "classzisa_1_1NetCDFFileStructure" ],
      [ "NetCDFFile", "classzisa_1_1NetCDFFile.html", "classzisa_1_1NetCDFFile" ],
      [ "NetCDFSerialWriter", "classzisa_1_1NetCDFSerialWriter.html", "classzisa_1_1NetCDFSerialWriter" ],
      [ "NetCDFWriter", "classzisa_1_1NetCDFWriter.html", "classzisa_1_1NetCDFWriter" ],
      [ "allocator", "classzisa_1_1allocator.html", "classzisa_1_1allocator" ],
      [ "AllocatorEquivalence", "structzisa_1_1AllocatorEquivalence.html", null ],
      [ "indexing_traits", "structzisa_1_1indexing__traits.html", null ],
      [ "array_traits", "structzisa_1_1array__traits.html", "structzisa_1_1array__traits" ],
      [ "array_base", "classzisa_1_1array__base.html", "classzisa_1_1array__base" ],
      [ "array", "classzisa_1_1array.html", "classzisa_1_1array" ],
      [ "default_dispatch_tag", "structzisa_1_1default__dispatch__tag.html", null ],
      [ "split_array_dispatch_tag", "structzisa_1_1split__array__dispatch__tag.html", null ],
      [ "bool_dispatch_tag", "structzisa_1_1bool__dispatch__tag.html", null ],
      [ "array_save_traits", "structzisa_1_1array__save__traits.html", "structzisa_1_1array__save__traits" ],
      [ "array_save_traits< bool >", "structzisa_1_1array__save__traits_3_01bool_01_4.html", "structzisa_1_1array__save__traits_3_01bool_01_4" ],
      [ "array_traits< T * >", "structzisa_1_1array__traits_3_01T_01_5_01_4.html", "structzisa_1_1array__traits_3_01T_01_5_01_4" ],
      [ "array_view_base", "classzisa_1_1array__view__base.html", "classzisa_1_1array__view__base" ],
      [ "array_view", "classzisa_1_1array__view.html", "classzisa_1_1array__view" ],
      [ "array_const_view", "classzisa_1_1array__const__view.html", "classzisa_1_1array__const__view" ],
      [ "block_allocator", "classzisa_1_1block__allocator.html", "classzisa_1_1block__allocator" ],
      [ "locked_ptr", "classzisa_1_1locked__ptr.html", "classzisa_1_1locked__ptr" ],
      [ "column_major", "structzisa_1_1column__major.html", null ],
      [ "column_major< 1 >", "structzisa_1_1column__major_3_011_01_4.html", null ],
      [ "column_major< 2 >", "structzisa_1_1column__major_3_012_01_4.html", null ],
      [ "column_major< 3 >", "structzisa_1_1column__major_3_013_01_4.html", null ],
      [ "column_major< 4 >", "structzisa_1_1column__major_3_014_01_4.html", null ],
      [ "indexing_traits< column_major< 1 > >", "structzisa_1_1indexing__traits_3_01column__major_3_011_01_4_01_4.html", null ],
      [ "indexing_traits< column_major< 2 > >", "structzisa_1_1indexing__traits_3_01column__major_3_012_01_4_01_4.html", null ],
      [ "indexing_traits< column_major< 3 > >", "structzisa_1_1indexing__traits_3_01column__major_3_013_01_4_01_4.html", null ],
      [ "indexing_traits< column_major< 4 > >", "structzisa_1_1indexing__traits_3_01column__major_3_014_01_4_01_4.html", null ],
      [ "contiguous_memory_base", "classzisa_1_1contiguous__memory__base.html", "classzisa_1_1contiguous__memory__base" ],
      [ "host_memory_resource", "classzisa_1_1host__memory__resource.html", "classzisa_1_1host__memory__resource" ],
      [ "memory_resource", "classzisa_1_1memory__resource.html", "classzisa_1_1memory__resource" ],
      [ "row_major", "structzisa_1_1row__major.html", null ],
      [ "row_major< 1 >", "structzisa_1_1row__major_3_011_01_4.html", null ],
      [ "row_major< 2 >", "structzisa_1_1row__major_3_012_01_4.html", null ],
      [ "row_major< 3 >", "structzisa_1_1row__major_3_013_01_4.html", null ],
      [ "row_major< 4 >", "structzisa_1_1row__major_3_014_01_4.html", null ],
      [ "indexing_traits< row_major< 1 > >", "structzisa_1_1indexing__traits_3_01row__major_3_011_01_4_01_4.html", null ],
      [ "indexing_traits< row_major< 2 > >", "structzisa_1_1indexing__traits_3_01row__major_3_012_01_4_01_4.html", null ],
      [ "indexing_traits< row_major< 3 > >", "structzisa_1_1indexing__traits_3_01row__major_3_013_01_4_01_4.html", null ],
      [ "indexing_traits< row_major< 4 > >", "structzisa_1_1indexing__traits_3_01row__major_3_014_01_4_01_4.html", null ],
      [ "ScientificConstructor", "structzisa_1_1ScientificConstructor.html", null ],
      [ "shape_t", "structzisa_1_1shape__t.html", "structzisa_1_1shape__t" ],
      [ "STDAllocatorEquivalence", "structzisa_1_1STDAllocatorEquivalence.html", "structzisa_1_1STDAllocatorEquivalence" ]
    ] ],
    [ "array_base", "classarray__base.html", null ]
];