name: Basic Integrity Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        compiler: [[gcc, g++], [clang, clang++]]
        zisa_has_mpi: [0, 1]
        zisa_has_netcdf: [0, 1]
        zisa_has_hdf5: [0, 1]

    env:
      ZISA_COMPONENT: ZisaMemory
      COMPILER: ${{ matrix.compiler[0] }}
      ZISA_HAS_MPI: ${{ matrix.zisa_has_mpi }}
      ZISA_HAS_HDF5: ${{ matrix.zisa_has_hdf5}}
      ZISA_HAS_NETCDF: ${{ matrix.zisa_has_netcdf }}
      REL_INSTALL_ROOT: zisa_dependencies
      CC: ${{ matrix.compiler[0] }}
      CXX: ${{ matrix.compiler[1] }}

    steps:
      # Checks-out the repository.
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Update Ubuntu
        run: |
          sudo apt-get update -y

      - name: Install MPI
        if: matrix.zisa_has_mpi == 1
        run: |
          sudo apt-get install -y openmpi-bin libopenmpi-dev

      - name: Install HDF5
        if: matrix.zisa_has_hdf5 == 1
        run: |
          sudo apt-get install -y libhdf5-serial-dev

      - name: Install NetCDF
        if: matrix.zisa_has_netcdf == 1
        run: |
          sudo apt-get install -y libnetcdf-dev

      - name: Install dependencies
        run: |
          bin/install_dependencies.sh ${CC} ${HOME}/${REL_INSTALL_ROOT} \
                                      --zisa_has_mpi=${ZISA_HAS_MPI}

      - name: Configure build
        run: |
          export INSTALL_DIR=$(bin/install_dependencies.sh ${CC} ${HOME}/${REL_INSTALL_ROOT} \
                                                           --zisa_has_mpi=${ZISA_HAS_MPI} \
                                                           --print_install_dir)

          cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}/zisa \
                -DCMAKE_PREFIX_PATH=${INSTALL_DIR}/zisa/lib/cmake/zisa \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=${CC} \
                -DCMAKE_CXX_COMPILER=${CXX} \
                -DZISA_HAS_MPI=${ZISA_HAS_MPI} \
                -DZISA_HAS_HDF5=${ZISA_HAS_HDF5} \
                -DZISA_HAS_NETCDF=${ZISA_HAS_NETCDF} \
                -B build .

      - name: Build everything
        run: |
          cmake --build build --parallel $(nproc)

      - name: Install everything
        run: |
          cmake --install build

      - name: Run tests
        run: |
          ctest --test-dir build
