name: Basic Integrity Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [[gcc, g++]]
        zisa_has_mpi: [0]

    env:
      COMPILER: ${{ matrix.compiler[0] }}
      ZISA_HAS_MPI: ${{ matrix.zisa_has_mpi }}
      INSTALL_ROOT: ${{ home }}/zisa_dependencies
      CC: ${{ matrix.compiler[0] }}
      CXX: ${{ matrix.compiler[1] }}

    steps:
      # Checks-out the repository.
      - uses: actions/checkout@v2

      - name: Install SSH key
        env:
          ZISA_CORE_SSH_KEY: ${{ secrets.ZISA_CORE_SSH_KEY }}

        run: |
          mkdir -p ${HOME}/.ssh
          echo "${ZISA_CORE_SSH_KEY}" > ${HOME}/.ssh/id_ed25519_core
          chmod 700 ${HOME}/.ssh/id_ed25519_core
          echo "Host github.com" > ${HOME}/.ssh/config
          echo "    IdentityFile ~/.ssh/id_ed25519_core" >> ${HOME}/.ssh/config

      - name: Install MPI
        if: matrix.zisa_has_mpi == 1
        run: |
          sudo apt-get install -y openmpi-bin libopenmpi-dev

      - name: Install conan
        run: |
          pip3 install wheel setuptools
          pip3 install conan

      - name: Install dependencies
        run: |
          export PATH=${PATH}:${HOME}/.local/bin
          bin/install_dependencies.sh ${CC} ${INSTALL_ROOT}

      - name: Configure build
        run: |
          export INSTALL_DIR=$(bin/install_dir.sh ${CC} ${INSTALL_ROOT})
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}/zisa \
                -DCMAKE_PREFIX_PATH=${INSTALL_DIR}/zisa/lib/cmake/zisa \
                -DCMAKE_PROJECT_ZisaMemory_INCLUDE=${INSTALL_DIR}/conan/conan_paths.cmake \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=${CC} \
                -DCMAKE_CXX_COMPILER=${CXX} \
                -DZISA_HAS_MPI=${ZISA_HAS_MPI} \
                ..

      - name: Build everying
        run: |
          cd build
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest
